[server]
address = "127.0.0.1"
maxUploadSize = 25
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6FC"
textColor = "#172033"
font = "sans serif"